version: '3'

services:
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: boris1
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: tinkofftaxi
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - networks_one
  application:
    build: .
    container_name: application
    volumes:
      - data-volume:/var/lib/application/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tinkofftaxi
    ports:
      - 8081:8080
    networks:
      - networks_one
networks:
  networks_one:
volumes:
  data-volume: