version: '2'
services:
  web:
    restart: always
    build: .
    image: 38cc5be52191
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=boris1
      - POSTGRES_DB=tinkofftaxi
      - PGDATA=/var/lib/postgresql/data/pgdata
    #ports:
      #- 5432:5432
